// Generated from the Wikimedia Commons API (imageinfo + extmetadata). Every image allows commercial use.
export type Img = {
  slug: string; src: string; alt: string; place: string; title: string; sourcePage: string;
  originalUrl: string; creator: string; license: string; licenseUrl: string;
  attributionRequired: boolean; attribution: string; shareAlike: boolean;
};

export const images = [
  {
    "slug": "navea-valley",
    "src": "/images/navea-valley.jpg",
    "alt": "The Navea river valley seen from the Ponte Navea viewpoint",
    "place": "Ponte Navea viewpoint, San Xoán de Río",
    "title": "Val do río Navea 1.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Val_do_r%C3%ADo_Navea_1.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Val_do_r%C3%ADo_Navea_1.jpg/1920px-Val_do_r%C3%ADo_Navea_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Miguel Branco",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Val do río Navea 1.jpg\" by Miguel Branco, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "navea-valley-2",
    "src": "/images/navea-valley-2.jpg",
    "alt": "Wooded slopes of the Navea valley",
    "place": "Ponte Navea viewpoint, San Xoán de Río",
    "title": "Val do río Navea 3.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Val_do_r%C3%ADo_Navea_3.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Val_do_r%C3%ADo_Navea_3.jpg/1920px-Val_do_r%C3%ADo_Navea_3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Miguel Branco",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Val do río Navea 3.jpg\" by Miguel Branco, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "navea-taboazas",
    "src": "/images/navea-taboazas.jpg",
    "alt": "The Navea valley from As Taboazas",
    "place": "As Taboazas, Navea valley",
    "title": "Val do Navea As Taboazas.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Val_do_Navea_As_Taboazas.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/Val_do_Navea_As_Taboazas.jpg/1920px-Val_do_Navea_As_Taboazas.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Estevoaei",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Val do Navea As Taboazas.jpg\" by Estevoaei, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "fraga",
    "src": "/images/fraga.jpg",
    "alt": "Fraga (native forest) walked on the Ruta da Fraga",
    "place": "San Xoán de Río",
    "title": "76382042 Fragas de S.Xoan de Rio.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:76382042_Fragas_de_S.Xoan_de_Rio.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/76382042_Fragas_de_S.Xoan_de_Rio.jpg/1920px-76382042_Fragas_de_S.Xoan_de_Rio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "xolopi",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attributionRequired": true,
    "attribution": "\"76382042 Fragas de S.Xoan de Rio.jpg\" by xolopi, CC BY 3.0, via Wikimedia Commons (resized)",
    "shareAlike": false
  },
  {
    "slug": "fraga-2",
    "src": "/images/fraga-2.jpg",
    "alt": "Fraga woodland path, San Xoán de Río",
    "place": "San Xoán de Río",
    "title": "76382056 Fragas de S.Xoan de Rio2.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:76382056_Fragas_de_S.Xoan_de_Rio2.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/76382056_Fragas_de_S.Xoan_de_Rio2.jpg/1920px-76382056_Fragas_de_S.Xoan_de_Rio2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "xolopi",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attributionRequired": true,
    "attribution": "\"76382056 Fragas de S.Xoan de Rio2.jpg\" by xolopi, CC BY 3.0, via Wikimedia Commons (resized)",
    "shareAlike": false
  },
  {
    "slug": "os-biocos",
    "src": "/images/os-biocos.jpg",
    "alt": "Rocky gorge at Os Biocos, San Xoán de Río",
    "place": "Os Biocos, San Xoán de Río",
    "title": "33551582 Os Biocos(San Xoan de Rio).jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:33551582_Os_Biocos(San_Xoan_de_Rio).jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f8/33551582_Os_Biocos%28San_Xoan_de_Rio%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "creator": "xolopi",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attributionRequired": true,
    "attribution": "\"33551582 Os Biocos(San Xoan de Rio).jpg\" by xolopi, CC BY 3.0, via Wikimedia Commons (resized)",
    "shareAlike": false
  },
  {
    "slug": "biocos-observatory",
    "src": "/images/biocos-observatory.jpg",
    "alt": "The Os Biocos plateau and observatory, near the planned Rural Valley campus",
    "place": "Os Biocos, San Xoán de Río",
    "title": "33551561 Observatorio dos Biocos(San Xoan de Rio).jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:33551561_Observatorio_dos_Biocos(San_Xoan_de_Rio).jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/c/cc/33551561_Observatorio_dos_Biocos%28San_Xoan_de_Rio%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "creator": "xolopi",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attributionRequired": true,
    "attribution": "\"33551561 Observatorio dos Biocos(San Xoan de Rio).jpg\" by xolopi, CC BY 3.0, via Wikimedia Commons (resized)",
    "shareAlike": false
  },
  {
    "slug": "church",
    "src": "/images/church.jpg",
    "alt": "Parish church of San Xoán de Río",
    "place": "San Xoán de Río village",
    "title": "Rio-1.JPG",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Rio-1.JPG",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Rio-1.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "creator": "Ramon.reboledo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Rio-1.JPG\" by Ramon.reboledo, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "ponte-navea",
    "src": "/images/ponte-navea.jpg",
    "alt": "Roman-medieval bridge on the Vía Nova over the Navea",
    "place": "Ponte Navea (San Xoán de Río / A Pobra de Trives)",
    "title": "Ponte Navea (7163419451).jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ponte_Navea_(7163419451).jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Ponte_Navea_%287163419451%29.jpg/1920px-Ponte_Navea_%287163419451%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Álvaro Pérez Vilariño",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "attributionRequired": true,
    "attribution": "\"Ponte Navea (7163419451).jpg\" by Álvaro Pérez Vilariño, CC BY-SA 2.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "miliario",
    "src": "/images/miliario.jpg",
    "alt": "Roman milestone of the Vía Nova",
    "place": "Ponte Bibei area, A Pobra de Trives",
    "title": "MIliario romano.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:MIliario_romano.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/MIliario_romano.jpg/1920px-MIliario_romano.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Álvaro Pérez Vilariño",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "attributionRequired": true,
    "attribution": "\"MIliario romano.jpg\" by Álvaro Pérez Vilariño, CC BY-SA 2.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "ponte-bibei",
    "src": "/images/ponte-bibei.jpg",
    "alt": "The Bibei river from the Roman bridge",
    "place": "Ponte Bibei, A Pobra de Trives",
    "title": "Ponte do Bibei - Roman bridge.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ponte_do_Bibei_-_Roman_bridge.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Ponte_do_Bibei_-_Roman_bridge.jpg/1920px-Ponte_do_Bibei_-_Roman_bridge.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Álvaro Pérez Vilariño",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "attributionRequired": true,
    "attribution": "\"Ponte do Bibei - Roman bridge.jpg\" by Álvaro Pérez Vilariño, CC BY-SA 2.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "manzaneda-ski",
    "src": "/images/manzaneda-ski.jpg",
    "alt": "Aerial view of the Manzaneda mountain resort buildings",
    "place": "Manzaneda mountain resort",
    "title": "Aerial photograph of Manzaneda ski resort (1).jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Aerial_photograph_of_Manzaneda_ski_resort_(1).jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Aerial_photograph_of_Manzaneda_ski_resort_%281%29.jpg/1920px-Aerial_photograph_of_Manzaneda_ski_resort_%281%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Joseolgon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Aerial photograph of Manzaneda ski resort (1).jpg\" by Joseolgon, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "cabeza-manzaneda",
    "src": "/images/cabeza-manzaneda.jpg",
    "alt": "Summit of Cabeza de Manzaneda",
    "place": "Cabeza de Manzaneda",
    "title": "Cabeza Grande de Cabeza de Manzaneda.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cabeza_Grande_de_Cabeza_de_Manzaneda.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Cabeza_Grande_de_Cabeza_de_Manzaneda.jpg/1920px-Cabeza_Grande_de_Cabeza_de_Manzaneda.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "PepTheVoyager",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Cabeza Grande de Cabeza de Manzaneda.jpg\" by PepTheVoyager, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "montederramo",
    "src": "/images/montederramo.jpg",
    "alt": "Monastery of Santa María de Montederramo",
    "place": "Montederramo",
    "title": "Montederramo Mosteiro de Santa María 1.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Montederramo_Mosteiro_de_Santa_Mar%C3%ADa_1.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Montederramo_Mosteiro_de_Santa_Mar%C3%ADa_1.jpg/1920px-Montederramo_Mosteiro_de_Santa_Mar%C3%ADa_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Miguel Branco",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Montederramo Mosteiro de Santa María 1.jpg\" by Miguel Branco, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "castro-caldelas",
    "src": "/images/castro-caldelas.jpg",
    "alt": "Castle of Castro Caldelas",
    "place": "Castro Caldelas",
    "title": "Castelo de Castro Caldelas, exterior.JPG",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Castelo_de_Castro_Caldelas,_exterior.JPG",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Castelo_de_Castro_Caldelas%2C_exterior.JPG/1920px-Castelo_de_Castro_Caldelas%2C_exterior.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "HombreDHojalata",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attributionRequired": true,
    "attribution": "\"Castelo de Castro Caldelas, exterior.JPG\" by HombreDHojalata, CC BY-SA 3.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "sil-catamaran",
    "src": "/images/sil-catamaran.jpg",
    "alt": "The Sil canyon seen from a catamaran",
    "place": "Sil canyon, Ribeira Sacra",
    "title": "Desde o catamarán.001 - Canón do Sil.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Desde_o_catamar%C3%A1n.001_-_Can%C3%B3n_do_Sil.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Desde_o_catamar%C3%A1n.001_-_Can%C3%B3n_do_Sil.jpg/1920px-Desde_o_catamar%C3%A1n.001_-_Can%C3%B3n_do_Sil.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Fernando Losada Rodríguez",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Desde o catamarán.001 - Canón do Sil.jpg\" by Fernando Losada Rodríguez, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "sil-canyon",
    "src": "/images/sil-canyon.jpg",
    "alt": "Sil canyon walls and river",
    "place": "Sil canyon, Ribeira Sacra",
    "title": "Cañón del Sil 1.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ca%C3%B1%C3%B3n_del_Sil_1.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Ca%C3%B1%C3%B3n_del_Sil_1.jpg/1920px-Ca%C3%B1%C3%B3n_del_Sil_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Rahico",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Cañón del Sil 1.jpg\" by Rahico, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "sil-vineyards",
    "src": "/images/sil-vineyards.jpg",
    "alt": "Terraced vineyards above the Sil",
    "place": "Ribeira Sacra",
    "title": "Viñedos sobre el Sil - WLE Spain 2015.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Vi%C3%B1edos_sobre_el_Sil_-_WLE_Spain_2015.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Vi%C3%B1edos_sobre_el_Sil_-_WLE_Spain_2015.jpg/1920px-Vi%C3%B1edos_sobre_el_Sil_-_WLE_Spain_2015.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Raúl Hidalgo",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "attributionRequired": false,
    "attribution": "Raúl Hidalgo (CC0), via Wikimedia Commons, no attribution required",
    "shareAlike": false
  },
  {
    "slug": "mencia",
    "src": "/images/mencia.jpg",
    "alt": "Mencía grapes ripening in a Ribeira Sacra vineyard",
    "place": "Ribeira Sacra DO (Sober)",
    "title": "Uva Mencia.JPG",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Uva_Mencia.JPG",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Uva_Mencia.JPG/1920px-Uva_Mencia.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "SanchoPanzaXXI",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attributionRequired": true,
    "attribution": "\"Uva Mencia.JPG\" by SanchoPanzaXXI, CC BY-SA 3.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "chestnuts",
    "src": "/images/chestnuts.jpg",
    "alt": "Roasted chestnuts for a magosto",
    "place": "Galicia",
    "title": "Castañas magosto.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Casta%C3%B1as_magosto.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Casta%C3%B1as_magosto.jpg/1920px-Casta%C3%B1as_magosto.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "L.Miguel Bugallo Sánchez (Lmbuga)",
    "license": "Public domain",
    "licenseUrl": "",
    "attributionRequired": false,
    "attribution": "L.Miguel Bugallo Sánchez (Lmbuga) (Public domain), via Wikimedia Commons, no attribution required",
    "shareAlike": false
  },
  {
    "slug": "magosto",
    "src": "/images/magosto.jpg",
    "alt": "A magosto chestnut-roast gathering",
    "place": "A Estrada, Galicia",
    "title": "Magosto 2011-3.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Magosto_2011-3.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/0/05/Magosto_2011-3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "creator": "Lmbuga",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attributionRequired": true,
    "attribution": "\"Magosto 2011-3.jpg\" by Lmbuga, CC BY-SA 3.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "pulpo",
    "src": "/images/pulpo.jpg",
    "alt": "Pulpo á feira (Galician octopus) for events",
    "place": "Galicia",
    "title": "Ración de pulpo a feira.jpeg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Raci%C3%B3n_de_pulpo_a_feira.jpeg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Raci%C3%B3n_de_pulpo_a_feira.jpeg/1920px-Raci%C3%B3n_de_pulpo_a_feira.jpeg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Manuel Ramallo",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "attributionRequired": false,
    "attribution": "Manuel Ramallo (CC0), via Wikimedia Commons, no attribution required",
    "shareAlike": false
  },
  {
    "slug": "queimada",
    "src": "/images/queimada.jpg",
    "alt": "A queimada, the Galician fire-punch ritual",
    "place": "Galicia",
    "title": "Queimada Galicia 1.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Queimada_Galicia_1.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Queimada_Galicia_1.jpg/1920px-Queimada_Galicia_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Luis Miguel Bugallo Sánchez",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "attributionRequired": true,
    "attribution": "\"Queimada Galicia 1.jpg\" by Luis Miguel Bugallo Sánchez, CC BY-SA 3.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "gaita",
    "src": "/images/gaita.jpg",
    "alt": "Galician bagpipe (gaita) and tambourine",
    "place": "Galicia",
    "title": "Gaita e pandeiro.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gaita_e_pandeiro.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Gaita_e_pandeiro.jpg/1920px-Gaita_e_pandeiro.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Xinzo.lvp",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Gaita e pandeiro.jpg\" by Xinzo.lvp, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "entroido",
    "src": "/images/entroido.jpg",
    "alt": "Entroido (carnival) in Terra de Trives",
    "place": "Maceda, Manzaneda (Terra de Trives)",
    "title": "Entroido de Maceda de Trives 01.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Entroido_de_Maceda_de_Trives_01.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Entroido_de_Maceda_de_Trives_01.jpg/1920px-Entroido_de_Maceda_de_Trives_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Estevoaei",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Entroido de Maceda de Trives 01.jpg\" by Estevoaei, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "termas",
    "src": "/images/termas.jpg",
    "alt": "Outariz hot springs, Ourense",
    "place": "Outariz, Ourense city",
    "title": "Termas de Outariz.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Termas_de_Outariz.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Termas_de_Outariz.jpg/1920px-Termas_de_Outariz.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "José Antonio Gil Martínez",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "attributionRequired": true,
    "attribution": "\"Termas de Outariz.jpg\" by José Antonio Gil Martínez, CC BY 2.0, via Wikimedia Commons (resized)",
    "shareAlike": false
  },
  {
    "slug": "chestnut-tree",
    "src": "/images/chestnut-tree.jpg",
    "alt": "A centuries-old chestnut tree",
    "place": "Galicia",
    "title": "Castiñeiro centenario.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Casti%C3%B1eiro_centenario.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Casti%C3%B1eiro_centenario.jpg/1920px-Casti%C3%B1eiro_centenario.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Carmen Baldinger Schubnell",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Castiñeiro centenario.jpg\" by Carmen Baldinger Schubnell, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  },
  {
    "slug": "stone-house",
    "src": "/images/stone-house.jpg",
    "alt": "Stone house and hórreo granary typical of Ourense villages",
    "place": "Sobreira, Vilamarín (Ourense)",
    "title": "Hórreo e casa en Sobreira, Vilamarín.jpg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:H%C3%B3rreo_e_casa_en_Sobreira,_Vilamar%C3%ADn.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/H%C3%B3rreo_e_casa_en_Sobreira%2C_Vilamar%C3%ADn.jpg/1920px-H%C3%B3rreo_e_casa_en_Sobreira%2C_Vilamar%C3%ADn.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Estevoaei",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attributionRequired": true,
    "attribution": "\"Hórreo e casa en Sobreira, Vilamarín.jpg\" by Estevoaei, CC BY-SA 4.0, via Wikimedia Commons (resized)",
    "shareAlike": true
  }
] as const satisfies readonly Img[];

export type ImgSlug = (typeof images)[number]["slug"];

export const img = (slug: ImgSlug): Img => images.find((i) => i.slug === slug)!;
